-- USER SQL
CREATE USER &USER IDENTIFIED BY WorkShop1502###;

-- ADD ROLES
GRANT CONNECT TO &USER;
GRANT CONSOLE_DEVELOPER TO &USER;
GRANT DWROLE TO &USER;
GRANT OML_DEVELOPER TO &USER;
GRANT RESOURCE TO &USER;
ALTER USER &USER DEFAULT ROLE CONSOLE_DEVELOPER,DWROLE,OML_DEVELOPER;

-- ENABLE OML
ALTER USER &USER GRANT CONNECT THROUGH OML$PROXY;

-- QUOTA
ALTER USER &USER QUOTA 500M ON DATA;

-- REST ENABLE
BEGIN
    ORDS_ADMIN.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => &USER,
        p_url_mapping_type => BASE_PATH,
        p_url_mapping_pattern => &USER,
        p_auto_rest_auth=> TRUE
    );
    -- ENABLE DATA SHARING
    C##ADP$SERVICE.DBMS_SHARE.ENABLE_SCHEMA(
            SCHEMA_NAME => &USER,
            ENABLED => TRUE
    );
    commit;
END;
/